import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SideBar from '../components/SideBar'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>What's app 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SideBar/>
      
    </div>
  )
}
